#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# export LOG_LEVEL=${LOG_LEVEL:='INFO'}
# export GUNICORN_WORKERS=${GUNICORN_WORKERS:=2}

# gunicorn app.main:app \
#     --workers ${GUNICORN_WORKERS} \
#     --worker-class uvicorn.workers.UvicornWorker \
#     --bind 0.0.0.0:8000 \
#     --log-file - \
#     --log-level ${LOG_LEVEL} \
#     --worker-tmp-dir /dev/shm
